[phases.setup]
nixPkgs = [
    'python311Full',
    'python311Packages.pip',
    'python311Packages.virtualenv',
    'postgresql',
    'gcc',
    'zlib',
    'libjpeg',
    'libpng',
    'freetype',
    'lcms2',
    'libwebp',
    'tcl',
    'tk',
    'libffi',
    'openssl'
]


[phases.install]
cmds = [
    'python -m venv /app/venv --system-site-packages',
    '. /app/venv/bin/activate && pip install --break-system-packages -r requirements.txt'
]

[phases.build]
cmds = [
    'python -m venv /opt/venv',
    '. /opt/venv/bin/activate',
    'pip install -r requirements.txt'
]

[start]
cmd = 'gunicorn MyPortfolio.wsgi:application'

