# Generated by Django 4.2.20 on 2025-04-23 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0002_project_slug_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='projects'),
        ),
    ]
