# Generated by Django 4.2.17 on 2025-06-12 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0003_project_image4'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.RemoveField(
            model_name='project',
            name='programming_language',
        ),
        migrations.AddField(
            model_name='project',
            name='programming_language',
            field=models.ManyToManyField(blank=True, to='Portfolio.language'),
        ),
    ]
