# Generated by Django 4.2.17 on 2025-06-18 00:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Portfolio', '0004_language_remove_project_programming_language_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='programming_language',
            field=models.ManyToManyField(blank=True, to='Portfolio.language'),
        ),
    ]
